name: build and test feature branch
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps:
      #############################################################
      # 2- dowload code from feature branch , setup java 8 and check that source code is buildable
      ########################################################
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: pull and checkout from git repository
        run: |
           echo "pulling and checking out from git repository"

      - name: setup java 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: build with maven
        run: |
          mvn clean test package
          echo "build with maven"
  
  merge-feature-into-develop:
    runs-on: ubuntu-latest
    needs: build-feature
    if: ${{ success() }}
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0
      
      - name: MEerge to development branch
        if: ${{ success() }}
        run: |
          git config --global user.email "EMAIL-OF-WORKFLOW@USER"
          git config --global user.name "WORKFLOW-USER"
          git merge --no-ff --verbose origin/${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.number }}"

      - name: Push changes after merge
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.base_ref }}